### ISSUE TITLE
Open/import existing Angular2 project

### ISSUE THREAD

**Issue by Plutoz01** [angelozerr/angular2-eclipse#19]
It would be nice, if I can import a previously created Angular2-eclipse project (or create a new one with existing source) into workspace. In this case 'ng init' should not run, but an optional 'npm install' would be useful.

The motivation behind this is that many users exclude eclipse specific project files from git/svn but after a checkout from this repo it is not needed to use 'ng init'.

**Comment by angelozerr** [comment]
I'm sorry but I don't understand very well your problem? 

> It would be nice, if I can import a previously created Angular2-eclipse project

You can do that today, no? What is your problem?

**Comment by Plutoz01** [comment]
Sorry, I wasn't enough clear and maybe mixed 2 things:
1: I created a new Angular2 project, then I removed from the eclipse workspace and I searched the open project at wrong place: I tried File->Import instead of File -> Open project. So this part is fine.

2: After I created a new Angular2 project I added to git and ignored .project file. Then deleted project a from local and pulled it again from git repo. This is my real problem: I can't find any feature called like 'new Angular2 project with existing source code', so I created a new Angular2 project in the same folder. This triggered an unwanted 'ng init' command and I had to stopped the process manually. Instead of this it could be more useful if the project wizard optionally calls 'npm update' to get all dependencies.

I hope, this is enough clear now.

**Comment by angelozerr** [comment]
> After I created a new Angular2 project I added to git and ignored .project file

Why? If you do that you will have problem too with Java project, or other project kind.

> I can't find any feature called like 'new Angular2 project with existing source code'

If you use Import / Git / Project from Git, it will create an empty .project after import. The only thing that you will loose is the TypeScript Builder, otherwise it will work since Angular2 Eclipse, TypeScript IDE doesn't use Eclipse nature.

**Comment by angelozerr** [comment]
@Plutoz01 is my answer help you?

**Comment by angelozerr** [comment]
None answer, I close this issue.

**Comment by luisalves00** [comment]
If I do File>Import I cannot see "existing angular project", like with gradle or maven. If I have an existing project how the import is done?

**Comment by malakeel** [comment]
Not sure why this is closed !
This does not answer the OP question. I am having the same requirements. 
How do I import an existing Angular2 project created by another tool into eclipse as "Angular2 project" ?

**Comment by lmilton-ithaka** [comment]
I simply opened the project in eclipse. It worked. File-->Open Projects from File System

**Comment by TrXtR** [comment]
Using Open Projects will result in the project imported being closed and unable to be opened. 
This is due to lack of .project files.

The reason to ignore .project related files, is because of people that follow a pattern to make code ide agnostic.
With a java project this is resolved by using maven, which would be used to generate .project etc.
But there's no solution like with importing angular projects.

So when importing bulk angular projects (that dont contain ide dependant configuration files), for each project you have to create a new project that links to the content. This is cumbersome. 
So yes the sane solution to this is to for each project go and create eclipse .project files and make the project ide dependant.
Which breaks the pattern.

Previously, the solution could be to use angular ide, which now is not recommended and deprecated.
And so that leaves the cumbersome solution, or the pattern breaking one.

(necro becuse it's what comes up)
